name: Exercice

on:
  push:
    branches:
      - dev
      - "feat/**"
    paths:
      - "**.ts"
      - "specific_folder/**"
    paths-ignore:
      - "staging/**"
      - "specific_folder/**"
  pull_request:
    types: [opened, closed]
  schedule:
    - cron: "*/5 * * * *"
    - cron: "30 */1 * * *"
    - cron: "0 3 * * 2"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: echo "Hello world"
