name: Docker

on:
  push:

jobs:
  build:
    runs-on: self-hosted
    container: node:18
    defaults:
      run:
        working-directory: ./node-app
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Test
        run: npm run test
