name: Runners

on:
  push:

jobs:
  build:
    defaults:
      run:
        working-directory: ./node-app
    strategy:
      matrix:
        version: [12, 14, 16]
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}

      - name: Install dependencies
        run: npm install

      - name: Test
        run: npm run test
